@baseUrl = http://localhost:3000

### Login Admin
POST http://localhost:3001/auth/login
Content-Type: application/json
 
{
  "noHp": "0844433112",
  "password": "12345678"
}

### Get Me (Admin)
GET http://localhost:3001/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWo4MWx4cHYwMDAwNWt1YW5xOGoxcHlhIiwibm9IcCI6IjA4NDQ0MzMxMTIiLCJyb2xlIjoiU0VDVVJJVFkiLCJpYXQiOjE3NjU5MDc0NzAsImV4cCI6MTc2NTk5Mzg3MH0.Lbz4Fyc9KeyKQz7zUKEemgc6NBtDarRsZqxPD3-AlqI
### Get Users (Paginated)
GET http://localhost:3001/users?page=1&pageSize=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWo4MWx4cHYwMDAwNWt1YW5xOGoxcHlhIiwibm9IcCI6IjA4NDQ0MzMxMTIiLCJyb2xlIjoiU0VDVVJJVFkiLCJpYXQiOjE3NjU5MDc0MzAsImV4cCI6MTc2NTk5MzgzMH0.QawgdmTNT8MSQzDPy8yFYmg7GTKM18f9IoPji2eyddA
### Logout Admin
DELETE http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWloa2F6cnAwMDAwdnl4djcxdDFybndtIiwiZW1haWwiOiJhbGljZUBwcmlzbWEuaW8iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjQzMDI0MDMsImV4cCI6MTc2NDM4ODgwM30.GV-z55C4NgE2PMBTic1ke10YTVpnycc2A6teVerfst8

###
GET http://localhost:3001/attendance/attendance/recap
Content-Type: application/json